version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizzamdp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza-net
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - pizza-net

  backend:
    build: ./PizzaMDP
    ports:
      - "8080:8080"
    volumes:
      - ./data_persistence:/app/data
    networks:
      - pizza-net
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - pizza-net

networks:
  pizza-net:

volumes:
  postgres_data:
