version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizzamdp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza-net
    ports:
      - "5432:5432"

  backend:
    build: ./PizzaMDP
    ports:
      - "8080:8080"
    volumes:
      - ./data_persistence:/app/data
    networks:
      - pizza-net
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - pizza-net

networks:
  pizza-net:

volumes:
  postgres_data:
